### ISSUE TITLE
Relations Tree

### ISSUE THREAD

**Issue by papousek** [adaptive-learning/anatomy-tagging#18]
Support the following scenarios:
- [x] create a new relation
- [x] change one of the relation terms (typeahead on Latin, English and Czech name)
- [x] publish data 

Also add relations tree to the menu.

**Comment by papousek** [comment]
Nešlo by ten typeahead zapínat/vypínat checkboxem? Když bude odškrtnutý, bude se měnit stávající term. Když bude zaškrtnutý, budu nějaký dohledávat.

Při přidávání nové relace - bylo by možné aktualizovat i model na klientovi (next a strom)?

**Comment by slaweet** [comment]
Udelal jsem typeahead měnící term na poli "ID"
Novou relaci jsem zacal pridavat po ulozeni do stromu

**Comment by marekcierny** [comment]
Wow, tohle vypada velmi privetive, moc dekuju!
A to pridani nove relace "create a new relation" se da udelat pomoci te editace, rozumim dobre?

**Comment by slaweet** [comment]
Nová souvislost je pomoci tlacika [+]. Má sice předvyplněný první pojem, ale nemělo by ničemu vadit jej změnit.
