### ISSUE TITLE
Fix terms in upper case

### ISSUE THREAD

**Issue by slaweet** [adaptive-learning/anatomy-tagging#7]

**Comment by marekcierny** [comment]
I think we should be careful here not to loose some data regarding hierarchy of terms, as in some case (I tried to provide an exhaustive list below), the UPPER CASE is the only hint that the terms are superterms for the following (sub)terms:
A02.4.00.002	CINGULUM PECTORALE; CINGULUM MEMBRI SUPERIORIS
A14.1.03.003	MYELENCEPHALON; MEDULLA OBLONGATA; BULBUS
A14.1.03.010	PONS
A14.1.03.005	MESENCEPHALON
A14.2.02.002	NERVI CERVICALES [C1-C8]

This makes me thinking of how we can manage the hierarchy (as we probably will need to deviate from the basic TA hierarchy at some point). I reckon that and editable hierarchy tree would be hard to make, and we can get the same functionality by editing superterms. But, I believe that it would be useful to have a script that would show (in rigid, noneditable way) the hierarchy of our terms. Co myslíš, Víťo?

**Comment by slaweet** [comment]
I found our that we were already doing this in Latin names, so I just added it to English and Czech and run the script on znackuj.anatom.cz. Still needs to be published to anatom.cz
